/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import comunes.Conexion;
import comunes.comJCombox;
import comunes.comJSQL;
import comunes.comLlamadaBuscadorComun2;
import garra.Garra;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FrmAnimales extends javax.swing.JDialog {

    Garra conex;
    Statement ejecutar;
    ResultSet resultado;
    String sentencia;
    char operacion;
    DefaultTableModel tabla = new DefaultTableModel();

    /**
     * Creates new form FrmVoluntarios
     */
    public FrmAnimales(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtColorPelaje = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCodVet = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAnimales = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtFechaIngreso = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFechaSalida = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIdTipoServicio = new javax.swing.JTextField();
        comboGeneros = new javax.swing.JComboBox();
        btnBuscarVet = new javax.swing.JButton();
        txtNombreVet = new javax.swing.JTextField();
        txtDescripServicio = new javax.swing.JTextField();
        btnBuscarServicio = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("REGISTRO DE ANIMALES");

        jLabel2.setText("Id Animal:");

        jLabel3.setText("Nombre:");

        jLabel5.setText("Edad Aprox:");

        jLabel7.setText("Color pelaje:");

        jLabel8.setText("Género:");

        jLabel9.setText("Veterinario:");

        txtID.setEditable(false);
        txtID.setEnabled(false);

        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEdadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });

        txtColorPelaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorPelajeActionPerformed(evt);
            }
        });
        txtColorPelaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtColorPelajeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorPelajeKeyTyped(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtCodVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodVetActionPerformed(evt);
            }
        });
        txtCodVet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodVetKeyTyped(evt);
            }
        });

        btnAgregar.setText("Añadir");
        btnAgregar.setToolTipText("click para agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Aceptar");
        btnGuardar.setToolTipText("click para guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("click para cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnModificar.setText("Editar");
        btnModificar.setToolTipText("click para modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Suprimir");
        btnEliminar.setToolTipText("click para eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.setToolTipText("click para cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        tablaAnimales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Edad Aprox.", "Color Pelaje", "Fecha Ingreso", "Fecha Salida", "Género", "Veterinario", "Tipo Servicio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAnimales.getTableHeader().setReorderingAllowed(false);
        tablaAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAnimalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablaAnimalesMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAnimales);
        if (tablaAnimales.getColumnModel().getColumnCount() > 0) {
            tablaAnimales.getColumnModel().getColumn(0).setMinWidth(50);
            tablaAnimales.getColumnModel().getColumn(0).setMaxWidth(50);
            tablaAnimales.getColumnModel().getColumn(1).setMinWidth(80);
            tablaAnimales.getColumnModel().getColumn(1).setMaxWidth(80);
            tablaAnimales.getColumnModel().getColumn(2).setMinWidth(80);
            tablaAnimales.getColumnModel().getColumn(2).setMaxWidth(80);
            tablaAnimales.getColumnModel().getColumn(3).setMinWidth(80);
            tablaAnimales.getColumnModel().getColumn(3).setMaxWidth(80);
            tablaAnimales.getColumnModel().getColumn(4).setMinWidth(80);
            tablaAnimales.getColumnModel().getColumn(4).setMaxWidth(80);
            tablaAnimales.getColumnModel().getColumn(5).setMinWidth(80);
            tablaAnimales.getColumnModel().getColumn(5).setMaxWidth(80);
        }

        jLabel4.setText("Fecha Ingreso:");

        txtFechaIngreso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtFechaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaIngresoActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha Salida:");

        txtFechaSalida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtFechaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaSalidaActionPerformed(evt);
            }
        });

        jLabel10.setText("Tipo Servicio:");

        txtIdTipoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdTipoServicioActionPerformed(evt);
            }
        });
        txtIdTipoServicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdTipoServicioKeyTyped(evt);
            }
        });

        comboGeneros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscarVet.setText("...");
        btnBuscarVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVetActionPerformed(evt);
            }
        });

        btnBuscarServicio.setText("...");
        btnBuscarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarServicioActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("J:\\Garra\\garrita.png")); // NOI18N
        jLabel11.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)))
                .addContainerGap(259, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEdad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtColorPelaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboGeneros, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFechaIngreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(txtFechaSalida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIdTipoServicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                    .addComponent(txtCodVet, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreVet)
                                    .addComponent(txtDescripServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarVet)
                                    .addComponent(btnBuscarServicio)))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(txtColorPelaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(txtCodVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarVet)
                    .addComponent(txtNombreVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(txtIdTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarServicio))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnCerrar))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        accionAgregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        accionGuardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        accionCancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        accionModificar(); // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        accionEliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tablaAnimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAnimalesMouseClicked
        cargarCuadros();
    }//GEN-LAST:event_tablaAnimalesMouseClicked

    private void tablaAnimalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAnimalesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaAnimalesMouseEntered

    private void txtColorPelajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorPelajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorPelajeActionPerformed

    private void txtCodVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodVetActionPerformed
        btnGuardar.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodVetActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtEdad.grabFocus();
        } // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtEdadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtColorPelaje.grabFocus();
        } // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadKeyPressed

    private void txtColorPelajeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorPelajeKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            comboGeneros.grabFocus();
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtColorPelajeKeyPressed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'A' || car > 'z')) {
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        } // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtCodVetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodVetKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'A' || car > 'z')) {
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtCodVetKeyTyped

    private void txtColorPelajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorPelajeKeyTyped

    }//GEN-LAST:event_txtColorPelajeKeyTyped

    private void txtIdTipoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdTipoServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdTipoServicioActionPerformed

    private void txtIdTipoServicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdTipoServicioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdTipoServicioKeyTyped

    private void btnBuscarVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVetActionPerformed
        String sql = "select idVeterinario,Nombre "
                + "from veterinario where idVeterinario like '%"+txtCodVet.getText()+"%'";
        if (comLlamadaBuscadorComun2.BuscadorjDialog(sql, new String[] {"Cod","Nombre"},
                comJSQL.getCamposSQL(sql), new String[][] {{"idVeterinario","0"}}, new int[] {}, new int[]{620, 400}, new int[]{50,280}, "Nombre")) {
        comLlamadaBuscadorComun2.BuscadorjDialogetStringObjAlt(new Object[]{txtCodVet,txtNombreVet}, new int[]{1,2});

            txtIdTipoServicio.grabFocus();
            //modoediciondetalle = "1";
        }
    }//GEN-LAST:event_btnBuscarVetActionPerformed

    private void btnBuscarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarServicioActionPerformed
                String sql = "select idTipoServicio,Descripcion"
                + "from tiposervicio where idTipoServicio like '%"+txtIdTipoServicio.getText()+"%'";
        if (comLlamadaBuscadorComun2.BuscadorjDialog(sql, new String[] {"Cod","Nombre"},
                comJSQL.getCamposSQL(sql), new String[][] {{"idTipoServicio","0"}}, new int[] {}, new int[]{620, 400}, new int[]{50,280}, "Descripcion")) {
        comLlamadaBuscadorComun2.BuscadorjDialogetStringObjAlt(new Object[]{txtIdTipoServicio,txtDescripServicio}, new int[]{1,2});

        }
    }//GEN-LAST:event_btnBuscarServicioActionPerformed

    private void txtFechaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaIngresoActionPerformed

    private void txtFechaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaSalidaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAnimales dialog = new FrmAnimales(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarServicio;
    private javax.swing.JButton btnBuscarVet;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox comboGeneros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAnimales;
    private javax.swing.JTextField txtCodVet;
    private javax.swing.JTextField txtColorPelaje;
    private javax.swing.JTextField txtDescripServicio;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JFormattedTextField txtFechaIngreso;
    private javax.swing.JFormattedTextField txtFechaSalida;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIdTipoServicio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreVet;
    // End of variables declaration//GEN-END:variables

    private void inicio() {
        try {
            ejecutar = conex.getConexion().createStatement();
            Conexion con = new Conexion();
            con.estaConectado();
            con.cargarCombo("select * from genero", comboGeneros);
            mostrarVol();
            modoEdicion(false);
        } catch (SQLException ex) {
            Logger.getLogger(FrmAnimales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void modoEdicion(boolean bl) {
        txtID.setEnabled(bl);
        txtNombre.setEnabled(bl);
        txtEdad.setEnabled(bl);
        txtColorPelaje.setEnabled(bl);
        txtCodVet.setEnabled(bl);
        comboGeneros.setEnabled(bl);
        txtFechaIngreso.setEnabled(bl);
        txtFechaSalida.setEnabled(bl);
        txtIdTipoServicio.setEnabled(bl);
        txtNombreVet.setEnabled(bl);
        txtIdTipoServicio.setEnabled(bl);
        txtDescripServicio.setEnabled(bl);
        btnBuscarVet.setEnabled(bl);
        btnBuscarServicio.setEnabled(bl);
        
        btnAgregar.setEnabled(!bl);
        btnGuardar.setEnabled(bl);
        btnCancelar.setEnabled(bl);
        btnModificar.setEnabled(!bl);
        btnEliminar.setEnabled(!bl);
        btnCerrar.setEnabled(!bl);

 

        tablaAnimales.setEnabled(!bl);

    }

    private void accionAgregar() {
        sentencia = "SELECT MAX(idAnimales) FROM Animales";
        try {
            resultado = ejecutar.executeQuery(sentencia);
            resultado.first();
            limpiarCuadros();
            txtID.setText(Integer.toString(resultado.getInt(1) + 1));
            modoEdicion(true);
            operacion = 'A';
            txtNombre.grabFocus();
        } catch (SQLException ex) {
            Logger.getLogger(FrmAnimales.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void accionGuardar() {
        String id = txtID.getText();
        String nombre = txtNombre.getText();
        String edad = txtEdad.getText();
        String color = txtColorPelaje.getText();
        Date FechaIngreso = (Date) txtFechaIngreso.getValue();
        Date FechaSalida = (Date) txtFechaSalida.getValue();
        SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        String fecha1 = sdf.format(FechaIngreso);
        String fecha2 = sdf.format(FechaSalida);
        String genero = comJCombox.getComboxString(comboGeneros, 1);
        String veterinario = txtCodVet.getText();
        String tiposervicio = txtIdTipoServicio.getText();
        if (nombre.isEmpty() || edad.isEmpty() || color.isEmpty() || fecha1.isEmpty() || fecha2.isEmpty() || veterinario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe" + " ingresar datos", " Revise el casillero vacio", JOptionPane.ERROR_MESSAGE);
            txtNombre.grabFocus();
        }
        if (operacion == 'A') {
            sentencia = "INSERT INTO Animales VALUES('" + id + "','" + nombre + "','" + edad + "','" + color + "','" + fecha1 + "','" + fecha2 + "','" + genero + "','"+veterinario+"','"+tiposervicio+"')";
            System.out.println(sentencia);
        }
        if (operacion == 'M') {
            sentencia = "UPDATE Animales SET Nombre='" + nombre + "',Edad='" + edad + "',ColorPelaje='" + color + "',EdadAproximada = '" + edad + "',FechaIngreso='" + fecha1 + "',FechaSalida='" + fecha2 + "',Genero = "+genero+",idVeterinario = "+veterinario+"idTipoServicio = "+tiposervicio+" WHERE idAnimal='" + id + "'";
        }
        try {
            ejecutar.executeUpdate(sentencia);

        } catch (SQLException ex) {
            Logger.getLogger(FrmAnimales.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiarCuadros();
        mostrarVol();
        modoEdicion(false);
    }

    private void accionCancelar() {
        modoEdicion(false);
        limpiarCuadros();
    }

    private void accionModificar() {
        if (tablaAnimales.getSelectedRow() >= 0) {
            operacion = 'M';
            modoEdicion(true);
            txtNombre.grabFocus();
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun registro", "Seleccione...", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void accionEliminar() {
        int fsel = tablaAnimales.getSelectedRow();
        if (fsel >= 0) {
            String xid = tablaAnimales.getValueAt(fsel, 0).toString();
            String xdes = tablaAnimales.getValueAt(fsel, 1).toString();
            int resp = JOptionPane.showConfirmDialog(this, "Confirma que desea eliminar el Animal *" + xdes.toUpperCase() + "* del Sistema?", "Confirme...",
                    JOptionPane.YES_NO_OPTION);
            if (resp == JOptionPane.YES_OPTION) {
                sentencia = "DELETE FROM Animales WHERE idAnimales='" + xid + "'";
                try {
                    ejecutar.executeUpdate(sentencia);
                } catch (SQLException ex) {
                    Logger.getLogger(FrmAnimales.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            mostrarVol();
            limpiarCuadros();

        }
    }

    private void cargarCuadros() {
        int fsel = tablaAnimales.getSelectedRow();
        if (fsel >= 0) {
            String xid = tablaAnimales.getValueAt(fsel, 0).toString();
            sentencia = "SELECT `idAnimales`,`Nombre`,`Edad aprox`,`ColorPelaje`, DATE_FORMAT(`FechaIngreso`,'%d/%m/%Y'),DATE_FORMAT(`FechaSalida`,'%d/%m/%Y'),`idGenero`,Veterinario_idVeterinario,`Veterinario`,`TipoServicio_idTipoServicio`, `Servicio` FROM `garra`.`animales_vista` WHERE idAnimales = '" + xid + "'";
            try {
                resultado = ejecutar.executeQuery(sentencia);
                resultado.first();
                txtID.setText(resultado.getString(1));
                txtNombre.setText(resultado.getString(2));
                txtEdad.setText(resultado.getString(3));
                txtColorPelaje.setText(resultado.getString(4));
                txtFechaIngreso.setText(resultado.getString(5));
                txtFechaSalida.setText(resultado.getString(6));
                comJCombox.setComboxPosition(comboGeneros,resultado.getString(7),1);
                txtCodVet.setText(resultado.getString(8));
                txtNombreVet.setText(resultado.getString(9));
                txtIdTipoServicio.setText(resultado.getString(10));
                txtDescripServicio.setText(resultado.getString(11));

            } catch (SQLException ex) {
                Logger.getLogger(FrmAnimales.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    private void limpiarCuadros() {
        txtNombre.setText(null);
        txtEdad.setText(null);
        txtColorPelaje.setText(null);
        comboGeneros.setSelectedIndex(0);
        txtID.setText(null);
        txtCodVet.setText(null);
        txtFechaIngreso.setText(null);

    }

    private void mostrarVol() {
        tabla.setRowCount(0);
        tabla = (DefaultTableModel) tablaAnimales.getModel();
        sentencia = "SELECT `idAnimales`,`Nombre`,`Edad aprox`,`ColorPelaje`, `FechaIngreso`,`FechaSalida`,`idGenero`,Veterinario_idVeterinario,`Veterinario`,`TipoServicio_idTipoServicio`, `Servicio` FROM `garra`.`animales_vista`;";
        try {
            resultado = ejecutar.executeQuery(sentencia);
            while (resultado.next()) {
                Object fila[] = new Object[10];
                fila[0] = resultado.getInt(1);
                fila[1] = resultado.getString(2);
                fila[2] = resultado.getString(3);
                fila[3] = resultado.getString(4);
                fila[4] = resultado.getString(5);
                fila[5] = resultado.getString(6);
                fila[6] = resultado.getString(7);
                fila[7] = resultado.getString(8);
                fila[8] = resultado.getString(9);
                fila[9] = resultado.getString(10);

                tabla.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmAnimales.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
