/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Frames;
import garra.Garra;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Usuario
 */
public class FrmProveedores extends javax.swing.JDialog {
 Garra conex;
    Statement ejecutar;
    ResultSet resultado;
    String sentencia;
    char operacion;
    DefaultTableModel tabla = new DefaultTableModel();
    /**
     * Creates new form FrmProveedores
     */
    public FrmProveedores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
          this.setLocationRelativeTo(null);
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDescripprov = new javax.swing.JTextField();
        txtIDprov = new javax.swing.JTextField();
        btnAgregar3 = new javax.swing.JButton();
        btnGuardar3 = new javax.swing.JButton();
        btnCancelar3 = new javax.swing.JButton();
        btnModificar3 = new javax.swing.JButton();
        btnEliminar3 = new javax.swing.JButton();
        btnCerrar3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtRUC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 0));
        jLabel13.setText("REGISTRO DE PROVEEDORES");

        jLabel15.setText("Id Proveedor:");

        jLabel16.setText("Descripcion:");

        txtDescripprov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescripprovKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripprovKeyTyped(evt);
            }
        });

        txtIDprov.setEditable(false);
        txtIDprov.setEnabled(false);

        btnAgregar3.setText("Añadir");
        btnAgregar3.setToolTipText("click para agregar");
        btnAgregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar3ActionPerformed(evt);
            }
        });

        btnGuardar3.setText("Aceptar");
        btnGuardar3.setToolTipText("click para guardar");
        btnGuardar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar3ActionPerformed(evt);
            }
        });

        btnCancelar3.setText("Cancelar");
        btnCancelar3.setToolTipText("click para cancelar");
        btnCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar3ActionPerformed(evt);
            }
        });

        btnModificar3.setText("Editar");
        btnModificar3.setToolTipText("click para modificar");
        btnModificar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar3ActionPerformed(evt);
            }
        });

        btnEliminar3.setText("Suprimir");
        btnEliminar3.setToolTipText("click para eliminar");
        btnEliminar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar3ActionPerformed(evt);
            }
        });

        btnCerrar3.setText("Cerrar");
        btnCerrar3.setToolTipText("click para cerrar");
        btnCerrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar3ActionPerformed(evt);
            }
        });

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ruc/CI", "Descripcion", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProveedores.getTableHeader().setReorderingAllowed(false);
        tablaProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProveedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablaProveedoresMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProveedores);
        if (tablaProveedores.getColumnModel().getColumnCount() > 0) {
            tablaProveedores.getColumnModel().getColumn(0).setMinWidth(50);
            tablaProveedores.getColumnModel().getColumn(0).setMaxWidth(50);
            tablaProveedores.getColumnModel().getColumn(1).setMinWidth(80);
            tablaProveedores.getColumnModel().getColumn(1).setMaxWidth(80);
            tablaProveedores.getColumnModel().getColumn(2).setMinWidth(80);
            tablaProveedores.getColumnModel().getColumn(2).setMaxWidth(80);
            tablaProveedores.getColumnModel().getColumn(3).setMinWidth(80);
            tablaProveedores.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jLabel1.setText("RUC/CI:");

        txtRUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRUCKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRUCKeyTyped(evt);
            }
        });

        jLabel2.setText("Nro Telf:");

        txttel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelKeyTyped(evt);
            }
        });

        jLabel3.setText("Direccion:");

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("J:\\Garra\\garrita.png")); // NOI18N
        jLabel11.setText("jLabel4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAgregar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrar3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDprov, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdireccion)
                                    .addComponent(txtDescripprov, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(75, 75, 75)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtIDprov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtDescripprov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar3)
                            .addComponent(btnGuardar3)
                            .addComponent(btnCancelar3)
                            .addComponent(btnModificar3)
                            .addComponent(btnEliminar3)
                            .addComponent(btnCerrar3))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar3ActionPerformed
        accionAgregar();
    }//GEN-LAST:event_btnAgregar3ActionPerformed

    private void btnGuardar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar3ActionPerformed
        accionGuardar();
    }//GEN-LAST:event_btnGuardar3ActionPerformed

    private void btnCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar3ActionPerformed
        accionCancelar();
    }//GEN-LAST:event_btnCancelar3ActionPerformed

    private void btnModificar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar3ActionPerformed
        accionModificar(); // TODO add your handling code here:
    }//GEN-LAST:event_btnModificar3ActionPerformed

    private void btnEliminar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar3ActionPerformed
        accionEliminar();
    }//GEN-LAST:event_btnEliminar3ActionPerformed

    private void btnCerrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar3ActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrar3ActionPerformed

    private void tablaProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProveedoresMouseClicked
        cargarCuadros();
    }//GEN-LAST:event_tablaProveedoresMouseClicked

    private void tablaProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProveedoresMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaProveedoresMouseEntered

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
    btnGuardar3.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txtDescripprovKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripprovKeyPressed
         if (evt.getKeyCode()==evt.VK_ENTER){
            txtRUC.grabFocus();
        } // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripprovKeyPressed

    private void txtRUCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRUCKeyPressed
         if (evt.getKeyCode()==evt.VK_ENTER){
            txttel.grabFocus();
        } // TODO add your handling code here:
    }//GEN-LAST:event_txtRUCKeyPressed

    private void txttelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelKeyPressed
         if (evt.getKeyCode()==evt.VK_ENTER){
            txtdireccion.grabFocus();
        } // TODO add your handling code here:
    }//GEN-LAST:event_txttelKeyPressed

    private void txtDescripprovKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripprovKeyTyped

    }//GEN-LAST:event_txtDescripprovKeyTyped

    private void txtRUCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRUCKeyTyped
       char car = evt.getKeyChar();
        if((car < '0' || car > '9')){
            evt.consume(); 
        } // TODO add your handling code here:
    }//GEN-LAST:event_txtRUCKeyTyped

    private void txttelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelKeyTyped
        char car = evt.getKeyChar();
        if((car < '0' || car > '9')){
            evt.consume(); 
        }// TODO add your handling code here:
    }//GEN-LAST:event_txttelKeyTyped

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped
       char car = evt.getKeyChar();
        if((car < 'A' || car > 'z')){
            evt.consume(); 
        } // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmProveedores dialog = new FrmProveedores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar3;
    private javax.swing.JButton btnCancelar3;
    private javax.swing.JButton btnCerrar3;
    private javax.swing.JButton btnEliminar3;
    private javax.swing.JButton btnGuardar3;
    private javax.swing.JButton btnModificar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField txtDescripprov;
    private javax.swing.JTextField txtIDprov;
    private javax.swing.JTextField txtRUC;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables

    private void inicio() {
          try {
            ejecutar = conex.getConexion().createStatement();
            mostrarProveed();
            modoEdicion(false);
        } catch (SQLException ex) {
            Logger.getLogger(FrmProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
         }

    private void modoEdicion(boolean bl) {
        txtIDprov.setEnabled(bl);
        txtRUC.setEnabled(bl);
        txtDescripprov.setEnabled(bl);
        txtIDprov.setEnabled(bl);
        txttel.setEnabled(bl);
        txtdireccion.setEnabled(bl);
        
        btnAgregar3.setEnabled(!bl);
        btnGuardar3.setEnabled(bl);
        btnCancelar3.setEnabled(bl);
        btnModificar3.setEnabled(!bl);
        btnEliminar3.setEnabled(!bl);
        btnCerrar3.setEnabled(!bl);
        
        tablaProveedores.setEnabled(!bl);
        
      }

    private void accionAgregar() {
    sentencia = "SELECT MAX(idProveedores) FROM Proveedores";
        try {
            resultado = ejecutar.executeQuery(sentencia);
            resultado.first();
            limpiarCuadros();
            txtIDprov.setText(Integer.toString(resultado.getInt(1)+1));
            modoEdicion(true);
            operacion = 'A';
            txtDescripprov.grabFocus();
        } catch (SQLException ex) {
            Logger.getLogger(FrmProveedores.class.getName()).log(Level.SEVERE, null, ex);
        }    
        }

    private void accionGuardar() {
      String v1 = txtIDprov.getText();
      String v2 = txtDescripprov.getText();
      String v3 = txtRUC.getText();  
      String v4 = txttel.getText();
      String v5 = txtdireccion.getText();
        if (v2.isEmpty()||v3.isEmpty()||v4.isEmpty()||v5.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe"+ " ingresar datos"," Revise el casillero vacio",JOptionPane.ERROR_MESSAGE);
            txtDescripprov.grabFocus(); 
             }
         if (operacion == 'A') {
        sentencia = "INSERT INTO Proveedores VALUES('"+v1+"','"+v2+"','"+v3+"','"+v4+"','"+v5+"')";
         
         }
        if (operacion == 'M'){
            sentencia = "UPDATE Proveedores SET DescripProveedores='"+v2+"',Ruc='"+v3+"',NroTelCel='"+v4+"',Direccion='"+v5+"' WHERE idProveedores='"+v1+"'";
        }
        System.out.println(sentencia);
        try {
            ejecutar.executeUpdate(sentencia);
           
        } catch (SQLException ex) {
            Logger.getLogger(FrmProveedores.class.getName()).log(Level.SEVERE, null, ex);
    }
        limpiarCuadros();
        mostrarProveed();
        modoEdicion(false);
  
     }

    private void limpiarCuadros() {
        txtIDprov.setText(null);
        txtRUC.setText(null);
        txtDescripprov.setText(null);
        txttel.setText(null);
        txtdireccion.setText(null);
    }

    private void mostrarProveed() {
        tabla.setRowCount(0);
        tabla = (DefaultTableModel)tablaProveedores.getModel();
        sentencia = "SELECT * FROM Proveedores";
        try {
        resultado = ejecutar.executeQuery(sentencia);
        while(resultado.next()){
                Object fila[] = new Object[5];
                fila[0] = resultado.getInt(1);
                fila[1] = resultado.getString(2);
                fila[2] = resultado.getInt(3);
                fila[3] = resultado.getInt(4);
                fila[4] = resultado.getString(5);
             
             
                tabla.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmProveedores.class.getName()).log(Level.SEVERE, null, ex);
    }
  
    }

    private void accionCancelar() {
         modoEdicion(false);
       limpiarCuadros();
       }

    private void accionModificar() {
        if(tablaProveedores.getSelectedRow()>=0){
            operacion = 'M';
            modoEdicion(true);
            txtDescripprov.grabFocus();
       }else{
            JOptionPane.showMessageDialog(this,"No se ha seleccionado ningun registro","Seleccione...",JOptionPane.ERROR_MESSAGE);
        }
        }

    private void accionEliminar() {
             int fsel = tablaProveedores.getSelectedRow();
        if(fsel>=0){
             String xid = tablaProveedores.getValueAt(fsel, 0).toString();
             String xdes = tablaProveedores.getValueAt(fsel,1).toString();
             int resp = JOptionPane.showConfirmDialog(this, "Confirma que desea eliminar la Proveedores *"+xdes.toUpperCase()+"* del Sistema?","Confirme...",
                    JOptionPane.YES_NO_OPTION);
              if(resp == JOptionPane.YES_OPTION){
                sentencia = "DELETE FROM Proveedores WHERE idProveedores='"+xid+"'";
                 try {
                    ejecutar.executeUpdate(sentencia);
                } catch (SQLException ex) {
                    Logger.getLogger(FrmProveedores.class.getName()).log(Level.SEVERE, null, ex);
                } 

    }
              mostrarProveed();
              limpiarCuadros();
        }
        }

    private void cargarCuadros() {
             int fsel = tablaProveedores.getSelectedRow();
        if(fsel>=0){
             String xid = tablaProveedores.getValueAt(fsel, 0).toString();
              sentencia = "SELECT * FROM Proveedores WHERE idProveedores = '"+xid+"'";
            try {
                resultado = ejecutar.executeQuery(sentencia);
                resultado.first();
                txtIDprov.setText(resultado.getString(1));
                txtDescripprov.setText(resultado.getString(2));
                txtRUC.setText(resultado.getString(3));
                txttel.setText(resultado.getString(4));
                txtdireccion.setText(resultado.getString(5));
                
            } catch (SQLException ex) {
                Logger.getLogger(FrmProveedores.class.getName()).log(Level.SEVERE, null, ex);
            }  
 
     }
    }

}
