/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package garra;

import Frames.FrmAnimales;
import Frames.FrmApertura;
import Frames.FrmCaja;
import Frames.FrmCargos;
import Frames.FrmCategorias;
import Frames.FrmCierreCaja;
import Frames.FrmClasificacion;
import Frames.FrmCodicionPago;
import Frames.FrmConceptosNotaDebito;
import Frames.FrmFormaAbono;
import Frames.FrmFormaPago;
import Frames.FrmGeneros;
import Frames.FrmItems;
import Frames.FrmMarcas;
import Frames.FrmMonedas;
import Frames.FrmProveedores;
import Frames.FrmServicios;
import Frames.FrmSocioProtector;
import Frames.FrmVeterinarios;
import Frames.FrmVoluntarios;
import Frames.Listado;
import Frames.Usuario;
import cobros.Cobros;
import cobros.Donaciones;
import compras.ListadoCompras;
import compras.NotaCreditoCompra;
import compras.NotaDebitoCompra;
import comunes.Conexion;
import comunes.reportes;
import java.awt.Color;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {
 public static String idusuario="3", aliasusu="Chomi";
    /**
     * Creates new form Principal
     */
    public Principal() {
          initComponents();
        this.setTitle("Sistema Albergue - Usuario:  "+aliasusu);
        this.getContentPane().setBackground(Color.white);
        this.setExtendedState(6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        mregvolunt = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mregusu = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mreggen = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        mregtipserv = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        mregcat = new javax.swing.JMenuItem();
        mregclas = new javax.swing.JMenuItem();
        mregmarca = new javax.swing.JMenuItem();
        mregproveeed = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mapertura = new javax.swing.JMenuItem();
        mcierre = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mregcobros = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mregmone = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mregfctcomp = new javax.swing.JMenuItem();
        mregnotcred = new javax.swing.JMenuItem();
        mregnotdeb = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("J:\\Garra\\imagenfond.jpg")); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0)));
        jMenuBar1.setForeground(new java.awt.Color(0, 153, 0));

        jMenu1.setBackground(new java.awt.Color(51, 102, 0));
        jMenu1.setText("Registros");

        jMenu9.setText("Reg Voluntarios");

        mregvolunt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, 0));
        mregvolunt.setText("Voluntarios");
        mregvolunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mregvoluntActionPerformed(evt);
            }
        });
        jMenu9.add(mregvolunt);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuItem1.setText("Cargos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem1);

        mregusu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, 0));
        mregusu.setText("Usuarios");
        mregusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mregusuActionPerformed(evt);
            }
        });
        jMenu9.add(mregusu);

        jMenu1.add(jMenu9);

        jMenu8.setText("Reg Animales");

        mreggen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, 0));
        mreggen.setText(" Generos");
        mreggen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mreggenActionPerformed(evt);
            }
        });
        jMenu8.add(mreggen);

        jMenuItem28.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jMenuItem28.setText("Animales");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem28);

        mregtipserv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        mregtipserv.setText(" Tipos Servicios");
        mregtipserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mregtipservActionPerformed(evt);
            }
        });
        jMenu8.add(mregtipserv);

        jMenu1.add(jMenu8);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        jMenuItem2.setText("Reg Veterinarios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenu7.setText("Reg Items ");

        jMenuItem27.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, 0));
        jMenuItem27.setText("Item");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem27);

        mregcat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, 0));
        mregcat.setText("Categorias");
        mregcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mregcatActionPerformed(evt);
            }
        });
        jMenu7.add(mregcat);

        mregclas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, 0));
        mregclas.setText("Clasificacion");
        mregclas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mregclasActionPerformed(evt);
            }
        });
        jMenu7.add(mregclas);

        mregmarca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, 0));
        mregmarca.setText(" Marcas");
        mregmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mregmarcaActionPerformed(evt);
            }
        });
        jMenu7.add(mregmarca);

        mregproveeed.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        mregproveeed.setText("Proveedores");
        mregproveeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mregproveeedActionPerformed(evt);
            }
        });
        jMenu7.add(mregproveeed);

        jMenu1.add(jMenu7);

        jMenuItem29.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PERIOD, 0));
        jMenuItem29.setText("Reg Socios Protectores");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem29);

        jMenuItem31.setText("Formas de Abono");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem31);

        jMenuItem33.setText("Conceptos Nota de Débito");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem33);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Caja");

        mapertura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, 0));
        mapertura.setText("Apertura Caja");
        mapertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maperturaActionPerformed(evt);
            }
        });
        jMenu5.add(mapertura);

        mcierre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_9, 0));
        mcierre.setText("Cierre Caja");
        mcierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcierreActionPerformed(evt);
            }
        });
        jMenu5.add(mcierre);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, 0));
        jMenuItem3.setText("Donaciones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem32.setText("Registrar cajas");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem32);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Cobros");

        mregcobros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, 0));
        mregcobros.setText("Reg Cobros");
        mregcobros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mregcobrosActionPerformed(evt);
            }
        });
        jMenu2.add(mregcobros);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, 0));
        jMenuItem4.setText("Reg Condicion Pago");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, 0));
        jMenuItem5.setText("Reg Forma de Pago");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        mregmone.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, 0));
        mregmone.setText("Monedas");
        mregmone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mregmoneActionPerformed(evt);
            }
        });
        jMenu2.add(mregmone);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Facturacion");

        mregfctcomp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, 0));
        mregfctcomp.setText("Reg Factura Compra");
        mregfctcomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mregfctcompActionPerformed(evt);
            }
        });
        jMenu3.add(mregfctcomp);

        mregnotcred.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        mregnotcred.setText("Reg Nota Credito");
        mregnotcred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mregnotcredActionPerformed(evt);
            }
        });
        jMenu3.add(mregnotcred);

        mregnotdeb.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, 0));
        mregnotdeb.setText("Reg Nota Debito");
        mregnotdeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mregnotdebActionPerformed(evt);
            }
        });
        jMenu3.add(mregnotdeb);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Informes");

        jMenu10.setText("Inf Voluntarios");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItem6.setText("Inf Voluntarios");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem6);

        jMenu6.add(jMenu10);

        jMenuItem30.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_INSERT, 0));
        jMenuItem30.setText("Inf Socio Protectores");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem30);

        jMenu11.setText("Inf Animales");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        jMenuItem7.setText("Inf Animales");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem7);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem12.setText("Inf Tipo Servicios");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem12);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem11.setText("Inf Genros");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem11);

        jMenu6.add(jMenu11);

        jMenu15.setText("Inf Cobros");

        jMenuItem22.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, 0));
        jMenuItem22.setText("Inf Donaciones");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem22);

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem17.setText("Inf Moneda");
        jMenu15.add(jMenuItem17);

        jMenuItem34.setText("Inf Cobros");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem34);

        jMenu6.add(jMenu15);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        jMenuItem8.setText("Inf Veterinarios");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenu12.setText("Inf Item");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItem9.setText("Inf Item");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItem10.setText("Inf Proveedores");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem10);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItem15.setText("Inf Categorias ");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem15);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem16.setText("Inf Casificacion");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem16);

        jMenuItem18.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, 0));
        jMenuItem18.setText("Inf Marcas");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem18);

        jMenu6.add(jMenu12);

        jMenuBar1.add(jMenu6);

        jMenu4.setText("Salir");

        mSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        jMenu4.add(mSalir);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1875, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1007, 1007, 1007))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mregvoluntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mregvoluntActionPerformed
       FrmVoluntarios  vvoluntarios = new FrmVoluntarios(this, true);
        vvoluntarios.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_mregvoluntActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmVeterinarios veterinarios = new FrmVeterinarios(this, true);
        veterinarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmCargos  cargos = new FrmCargos(this, true);
        cargos.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mregusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mregusuActionPerformed
        Usuario user = new Usuario(this, true);
        user.setVisible(true);
    }//GEN-LAST:event_mregusuActionPerformed

    private void mregcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mregcatActionPerformed
         FrmCategorias  vcat = new FrmCategorias(this, true);
        vcat.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mregcatActionPerformed

    private void mregfctcompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mregfctcompActionPerformed
        ListadoCompras compras = new ListadoCompras(this, true);
        compras.setVisible(true);
    }//GEN-LAST:event_mregfctcompActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
       System.exit(0);  // TODO add your handling code here:
    }//GEN-LAST:event_mSalirActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
    reportes reporte = new reportes();
      reporte.runreporte("Veterinarios");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
          reportes reporte = new reportes();
      reporte.runreporte("Marcas");
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         FrmFormaPago  vfp = new FrmFormaPago(this, true);
        vfp.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        FrmItems items = new FrmItems(this, true);
        items.setVisible(true);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
       reportes reporte = new reportes();
      reporte.runreporte("SocioProtector");
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void mreggenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mreggenActionPerformed
        FrmGeneros  vgen = new FrmGeneros(this, true);
        vgen.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_mreggenActionPerformed

    private void mregtipservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mregtipservActionPerformed
         FrmServicios  vser = new FrmServicios(this, true);
        vser.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mregtipservActionPerformed

    private void mregclasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mregclasActionPerformed
         FrmClasificacion  vclas = new FrmClasificacion(this, true);
        vclas.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mregclasActionPerformed

    private void mregmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mregmarcaActionPerformed
         FrmMarcas  vmarc = new FrmMarcas(this, true);
        vmarc.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mregmarcaActionPerformed

    private void mregproveeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mregproveeedActionPerformed
         FrmProveedores  vprov = new FrmProveedores(this, true);
        vprov.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mregproveeedActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FrmCodicionPago  vcp = new FrmCodicionPago(this, true);
        vcp.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mregmoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mregmoneActionPerformed
         FrmMonedas  vmon = new FrmMonedas(this, true);
        vmon.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_mregmoneActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        FrmAnimales animales = new FrmAnimales(this, true);
        animales.setVisible(true);
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
       FrmSocioProtector socioprotector = new FrmSocioProtector(this, true);
       socioprotector.setVisible(true);
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
       FrmFormaAbono formaabono= new FrmFormaAbono(this,true);
       formaabono.setVisible(true);
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void mregnotcredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mregnotcredActionPerformed
            NotaCreditoCompra creditocompra = new NotaCreditoCompra(this, true);
        Listado listado = new Listado(this, true, creditocompra, "Notas de Crédito - Compra",
                "notacreditocompra", "NroNotaCredito", "NroFacturacompra", 2, "NroNotaCredito,NroTimbrado,NroFact,NroTimbradoFactura,RUC,RazonSocial,Fecha",
                new String[]{"Número","Timbrado","Factura","Timbrado","RUC/CI","Proveedor","Fecha"}, false, new String[]{"ruc","RazonSocial"});
        listado.ventana = creditocompra;
        listado.setVisible(true);
    }//GEN-LAST:event_mregnotcredActionPerformed

    private void mregnotdebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mregnotdebActionPerformed
             NotaDebitoCompra debitocompra = new NotaDebitoCompra(this, true);
        Listado listado = new Listado(this, true, debitocompra, "Notas de Débito - Compra",
                "notadebitocompra", "NroNotaDebitoCompra", "NroFacturacompra", 2, "NroNotaDebitoCompra,NroTimbrado,NroFact,NroTimbradoFactura,RUC,RazonSocial,Fecha",
                new String[]{"Número","Timbrado","Factura","Timbrado","RUC/CI","Proveedor","Fecha"}, false, new String[]{"ruc","RazonSocial"});
        listado.ventana = debitocompra;
        listado.setVisible(true);
    }//GEN-LAST:event_mregnotdebActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        FrmConceptosNotaDebito conceptos = new FrmConceptosNotaDebito(this, true);
        conceptos.setVisible(true);
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
      reportes reporte = new reportes();
      reporte.runreporte("Voluntarios");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
    reportes reporte = new reportes();
      reporte.runreporte("Animales");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
           reportes reporte = new reportes();
      reporte.runreporte("Servicios"); 
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void mregcobrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mregcobrosActionPerformed
        Cobros cobro = new Cobros(this, true,"2");
        Listado listadocobros = new Listado(this, true, cobro, "Cobros", "cobros", "idCobros", "idVoluntario", 1, "`idCobros`,`idVoluntarios`,`Fecha`,`MontoEntregado`,`idSocioProtector`,`idCondicionPago`,`idAperturaCaja`", new String[]{"idcobro","idvoluntario","fecha","monto","idsocio","idcondicion","idapertura"}, false, new String[]{"idCobros"});
        listadocobros.ventana = cobro;
        listadocobros.setVisible(true);
    }//GEN-LAST:event_mregcobrosActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
           reportes reporte = new reportes();
      reporte.runreporte("Donaciones");
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        reportes reporte = new reportes();
        reporte.runreporte("Cobros");
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
            reportes reporte = new reportes();
        reporte.runreporte("Items");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
          reportes reporte = new reportes();
        reporte.runreporte("Proveedores");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
                reportes reporte = new reportes();
        reporte.runreporte("Categorias");
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        reportes reporte = new reportes();
        reporte.runreporte("Clasificacion");
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        FrmCaja caja = new FrmCaja(this,true);
        caja.setVisible(true);
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Donaciones donaciones = new Donaciones(this, true, "2");
        Listado listadodonaciones = new Listado(this, true, donaciones, "Donaciones", "donaciones", "idDonaciones", "DescripDonaciones", 1, "`idDonaciones`,`DescripDonaciones`,`CantidadMonto`,`idMonedas`,`idAperturaCaja`,fecha", new String[]{"idDonaciones","DescripDonaciones","monto","idapertura,fecha"}, false, new String[]{"idDonaciones"});
        listadodonaciones.ventana = donaciones;
        listadodonaciones.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mcierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcierreActionPerformed
        FrmCierreCaja cierre = new FrmCierreCaja(this, true);
        cierre.setVisible(true);
    }//GEN-LAST:event_mcierreActionPerformed

    private void maperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maperturaActionPerformed
        FrmApertura apertura = new FrmApertura(this, true);
        apertura.setVisible(true);
    }//GEN-LAST:event_maperturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenuItem mapertura;
    private javax.swing.JMenuItem mcierre;
    private javax.swing.JMenuItem mregcat;
    private javax.swing.JMenuItem mregclas;
    private javax.swing.JMenuItem mregcobros;
    private javax.swing.JMenuItem mregfctcomp;
    private javax.swing.JMenuItem mreggen;
    private javax.swing.JMenuItem mregmarca;
    private javax.swing.JMenuItem mregmone;
    private javax.swing.JMenuItem mregnotcred;
    private javax.swing.JMenuItem mregnotdeb;
    private javax.swing.JMenuItem mregproveeed;
    private javax.swing.JMenuItem mregtipserv;
    private javax.swing.JMenuItem mregusu;
    private javax.swing.JMenuItem mregvolunt;
    // End of variables declaration//GEN-END:variables
}
